<?php

namespace Database\Seeders;

use App\Models\CmsBlock;
use Illuminate\Database\Seeder;

class CmsBlockSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->blocks() as $attrs) {
            $model = CmsBlock::withTrashed()->firstOrNew([
                'page' => $attrs['page'],
                'section_key' => $attrs['section_key'],
                'sort_order' => $attrs['sort_order'],
            ]);
            $model->fill($attrs);
            $model->deleted_at = null;
            $model->save();
        }
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function blocks(): array
    {
        return [
            // —— About ——
            [
                'page' => 'about',
                'section_key' => 'hero',
                'sort_order' => 0,
                'title_en' => 'About Us',
                'title_de' => 'Über uns',
                'body_en' => 'We connect you with trusted, professional cleaners across Germany.',
                'body_de' => 'Wir verbinden Sie mit vertrauenswürdigen Reinigungsfachleuten in Deutschland.',
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'about',
                'section_key' => 'mission',
                'sort_order' => 0,
                'title_en' => 'Our Mission',
                'title_de' => 'Unsere Mission',
                'body_en' => 'We believe everyone deserves a clean living space. Our platform makes it easy to find reliable, background-checked cleaning professionals — especially for the international community in Germany.',
                'body_de' => 'Wir glauben, dass jeder ein sauberes Zuhause verdient. Unsere Plattform macht es einfach, zuverlässige, überprüfte Reinigungsfachleute zu finden.',
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'about',
                'section_key' => 'values_heading',
                'sort_order' => 0,
                'title_en' => 'Our Values',
                'title_de' => 'Unsere Werte',
                'body_en' => null,
                'body_de' => null,
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'about',
                'section_key' => 'value',
                'sort_order' => 0,
                'title_en' => 'Trust & Transparency',
                'title_de' => 'Vertrauen & Transparenz',
                'body_en' => 'Every cleaner is background-checked and legally registered. No hidden fees, no surprises.',
                'body_de' => 'Jeder Reiniger ist überprüft und rechtlich registriert. Keine versteckten Gebühren.',
                'icon' => 'shield',
                'is_active' => true,
            ],
            [
                'page' => 'about',
                'section_key' => 'value',
                'sort_order' => 1,
                'title_en' => 'Quality First',
                'title_de' => 'Qualität zuerst',
                'body_en' => 'We maintain high standards through customer reviews and our satisfaction guarantee program.',
                'body_de' => 'Wir halten hohe Standards durch Kundenbewertungen und unser Zufriedenheitsgarantie-Programm.',
                'icon' => 'sparkles',
                'is_active' => true,
            ],
            [
                'page' => 'about',
                'section_key' => 'value',
                'sort_order' => 2,
                'title_en' => 'Accessibility',
                'title_de' => 'Zugänglichkeit',
                'body_en' => 'English-speaking cleaners and support available at no extra cost, making life easier for internationals.',
                'body_de' => 'Englischsprachige Reiniger und Support ohne Aufpreis verfügbar.',
                'icon' => 'globe',
                'is_active' => true,
            ],

            // —— Contact ——
            [
                'page' => 'contact',
                'section_key' => 'hero',
                'sort_order' => 0,
                'title_en' => 'Get in Touch',
                'title_de' => 'Kontakt',
                'body_en' => 'Have a question or need a custom quote? We\'d love to hear from you.',
                'body_de' => 'Haben Sie eine Frage oder benötigen ein Angebot? Wir freuen uns auf Ihre Nachricht.',
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'contact',
                'section_key' => 'form_intro',
                'sort_order' => 0,
                'title_en' => 'Send a Message',
                'title_de' => 'Nachricht senden',
                'body_en' => null,
                'body_de' => null,
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'contact',
                'section_key' => 'sidebar',
                'sort_order' => 0,
                'title_en' => 'Office Cleaning Quote',
                'title_de' => 'Büroreinigung Angebot',
                'body_en' => 'Need a custom cleaning plan for your office? Fill out the form and we\'ll get back to you within 24 hours.',
                'body_de' => 'Benötigen Sie einen individuellen Reinigungsplan für Ihr Büro? Füllen Sie das Formular aus — wir melden uns innerhalb von 24 Stunden.',
                'icon' => null,
                'is_active' => true,
            ],

            // —— Cities ——
            [
                'page' => 'cities',
                'section_key' => 'hero',
                'sort_order' => 0,
                'title_en' => 'Cities We Serve',
                'title_de' => 'Unsere Städte',
                'body_en' => 'Professional cleaning services available in major German cities.',
                'body_de' => 'Professionelle Reinigungsservices in deutschen Großstädten.',
                'icon' => null,
                'is_active' => true,
            ],

            // —— Services listing ——
            [
                'page' => 'services',
                'section_key' => 'hero',
                'sort_order' => 0,
                'title_en' => 'Our Cleaning Services',
                'title_de' => 'Unsere Reinigungsservices',
                'body_en' => 'Compare options and find the perfect cleaning service for your needs.',
                'body_de' => 'Vergleichen Sie Optionen und finden Sie den perfekten Service.',
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'services',
                'section_key' => 'subscription_heading',
                'sort_order' => 0,
                'title_en' => 'Subscription',
                'title_de' => 'Abonnement',
                'body_en' => null,
                'body_de' => null,
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'services',
                'section_key' => 'onetime_heading',
                'sort_order' => 0,
                'title_en' => 'One-Time',
                'title_de' => 'Einmalig',
                'body_en' => null,
                'body_de' => null,
                'icon' => null,
                'is_active' => true,
            ],

            // —— Home ——
            [
                'page' => 'home',
                'section_key' => 'hero',
                'sort_order' => 0,
                'title_en' => 'Premium Cleaning Services',
                'title_de' => 'Premium-Reinigungsservice',
                'body_en' => 'Book a verified, background-checked cleaner for your home or office in Germany.',
                'body_de' => 'Buchen Sie einen geprüften Reinigungsfachmann für Ihr Zuhause oder Büro in Deutschland.',
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section_key' => 'how_section',
                'sort_order' => 0,
                'title_en' => 'How It Works',
                'title_de' => 'So funktioniert\'s',
                'body_en' => null,
                'body_de' => null,
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section_key' => 'how_step',
                'sort_order' => 1,
                'title_en' => 'Book Online',
                'title_de' => 'Online buchen',
                'body_en' => 'Select your service, set the date & time, and provide your address. Choose from a range of special requests.',
                'body_de' => 'Wählen Sie Ihren Service, legen Sie Datum und Uhrzeit fest und geben Sie Ihre Adresse an.',
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section_key' => 'how_step',
                'sort_order' => 2,
                'title_en' => 'Pay the Deposit',
                'title_de' => 'Anzahlung leisten',
                'body_en' => 'Secure your booking with a one-hour deposit. The amount is deducted from your final bill.',
                'body_de' => 'Sichern Sie Ihre Buchung mit einer Anzahlung für die erste Stunde. Der Betrag wird von der Endrechnung abgezogen.',
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section_key' => 'how_step',
                'sort_order' => 3,
                'title_en' => 'Enjoy a Clean Space',
                'title_de' => 'Sauberkeit genießen',
                'body_en' => 'Your verified cleaner arrives on schedule. After service, receive a summary and pay the balance.',
                'body_de' => 'Ihr verifizierter Reiniger kommt pünktlich. Nach dem Service erhalten Sie eine Zusammenfassung.',
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section_key' => 'services_intro',
                'sort_order' => 0,
                'title_en' => 'Our Services',
                'title_de' => 'Unsere Dienstleistungen',
                'body_en' => 'Professional cleaning tailored to your needs',
                'body_de' => 'Professionelle Reinigung nach Ihren Bedürfnissen',
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section_key' => 'reviews_heading',
                'sort_order' => 0,
                'title_en' => 'What Our Customers Say',
                'title_de' => 'Was unsere Kunden sagen',
                'body_en' => null,
                'body_de' => null,
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section_key' => 'cities_intro',
                'sort_order' => 0,
                'title_en' => 'Available Cities',
                'title_de' => 'Verfügbare Städte',
                'body_en' => 'We serve major cities across Germany',
                'body_de' => 'Wir bedienen große Städte in Deutschland',
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section_key' => 'trust_section',
                'sort_order' => 0,
                'title_en' => 'Why Choose Us',
                'title_de' => 'Warum wir?',
                'body_en' => null,
                'body_de' => null,
                'icon' => null,
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section_key' => 'trust_item',
                'sort_order' => 0,
                'title_en' => 'Background-Checked',
                'title_de' => 'Überprüft',
                'body_en' => 'All cleaners are verified and legally registered businesses.',
                'body_de' => 'Alle Reinigungskräfte sind überprüft und rechtlich registriert.',
                'icon' => 'trust_verified',
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section_key' => 'trust_item',
                'sort_order' => 1,
                'title_en' => 'English Speaking',
                'title_de' => 'Englischsprachig',
                'body_en' => 'Choose an English-speaking cleaner at no extra cost.',
                'body_de' => 'Wählen Sie einen englischsprachigen Reiniger ohne Aufpreis.',
                'icon' => 'trust_english',
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section_key' => 'trust_item',
                'sort_order' => 2,
                'title_en' => 'Satisfaction Guarantee',
                'title_de' => 'Zufriedenheitsgarantie',
                'body_en' => 'Request a correction cleaning within 24 hours if you\'re not satisfied.',
                'body_de' => 'Fordern Sie innerhalb von 24 Stunden eine Nachbesserung an.',
                'icon' => 'trust_guarantee',
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section_key' => 'trust_item',
                'sort_order' => 3,
                'title_en' => '7-Day Support',
                'title_de' => '7-Tage-Support',
                'body_en' => 'Customer support available every day of the week.',
                'body_de' => 'Kundenservice jeden Tag der Woche verfügbar.',
                'icon' => 'trust_support',
                'is_active' => true,
            ],
            [
                'page' => 'home',
                'section_key' => 'cta',
                'sort_order' => 0,
                'title_en' => 'Ready for a Spotless Home?',
                'title_de' => 'Bereit für ein sauberes Zuhause?',
                'body_en' => 'Book your first cleaning in under 60 seconds.',
                'body_de' => 'Buchen Sie Ihre erste Reinigung in unter 60 Sekunden.',
                'icon' => null,
                'is_active' => true,
            ],
        ];
    }
}
